nelmio_api_doc:
  documentation:
    info:
      title: "Library Management System"
      description: "API documentation for the Library Management System Application"
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api
